---
- name: Create Nat Gateway and associate private subnets
  cloudformation:
    stack_name: "NatGateway"
    state: "present"
    region: "{{ region }}"
    template: "roles/nat-gateway/files/nat-gateway.json"
    template_parameters:
        VPC: "{{ vpc }}"
        PublicSubnet: "{{ public_subnet1 }}"
        PrivateSub1: "{{ private_subnet1}}"
        PrivateSub2: "{{ private_subnet2}}"
        PrivateSub3: "{{ private_subnet3}}"
