---
# Run provision.yaml with higher number of nodes to create a new app-node VM
- include: provision.yaml

# Run config.yml to update openshift installation (add the new node(s))
- include: '{{ openshift_ansible_dir ~ "/playbooks/byo/config.yml" }}'

# Post-verification: Verify new number of nodes
# TODO: remove verification based on oc?, keep openstack_num_nodes
- hosts: masters
  tasks:
  - name: Get number of nodes
    shell: oc get nodes | grep app-node -c
    register: oc_new_result
  - name: Check that the actual number of nodes matches defined value
    assert:
      that: 'nodes | int == oc_new_result.stdout | int'
      msg: >
        FAIL: Number of application nodes has not been increased accordingly
        (it should be {{ nodes }} but it is {{ oc_new_result.stdout | int }}).
  - name: Check that current number of nodes has been updated in vars
    assert:
      that: 'nodes | int == openstack_num_nodes | int'
      msg: >
        FAIL: Number of application nodes has not been updated in vars
        (it should be {{ nodes }} but it is {{ openstack_num_nodes | int }}).
