---
ec2_region: us-east-1
ec2_image: ami-7e14f213
api_port: 443
console_port: 443

identity_providers:
- name: htpasswd_auth
  login: true
  challenge: true
  kind: HTPasswdPasswordIdentityProvider
  filename: /etc/origin/master/htpasswd

masters:
  count: "{{ num_masters | default(3) }}"
  instance_type: m4.xlarge
infra_nodes:
  count: "{{ num_infra_nodes | default(2) }}"
  instance_type: m4.xlarge
app_nodes:
  count: "{{ num_app_nodes | default(2) }}"
  instance_type: m4.xlarge
