---
- name: Launch instance infra node in Subnet1
  ec2:
     keypair: "{{ keypair }}"
     group: ose_infra_node_sg
     instance_type: "{{ node_instance_type }}"
     image: "{{ ami }}"
     wait: true
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 25
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: "{{ docker_storage }}"
         delete_on_termination: true
       - device_name: /dev/xvdc
         volume_type: gp2
         volume_size: "50"
         delete_on_termination: true
     region: "{{ region }}"
     vpc_subnet_id: "{{ private_subnet1 }}"
     instance_profile_name: ose-ebs
     instance_tags:
       Name: "{{ infra_instance_prefix }}01.{{ public_hosted_zone }}"
       openshift-role: "{{ infra_tag }}"
     count: 1
  register: infra0
- name: Launch instance infra node in Subnet2
  ec2:
     keypair: "{{ keypair }}"
     group: ose_infra_node_sg
     instance_type: "{{ node_instance_type }}"
     image: "{{ ami }}"
     wait: true
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 25
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: "{{ docker_storage }}"
         delete_on_termination: true
       - device_name: /dev/xvdc
         volume_type: gp2
         volume_size: "50"
         delete_on_termination: true
     region: "{{ region }}"
     vpc_subnet_id: "{{ private_subnet2 }}"
     instance_profile_name: ose-ebs
     instance_tags:
       Name: "{{ infra_instance_prefix }}02.{{ public_hosted_zone }}"
       openshift-role: "{{ infra_tag }}"
     count: 1
  register: infra1
