- name: 'Setup groups'
  hosts: localhost
  connection: local
  vars:
    env_cluster_hosts: "{{ groups.tags.['tag_environment_' ~ env_id]
                           | intersect(groups.tags.['tag_clusterid_' ~ cluster_id]) }}"
    master_hosts: "{{ groups.tags.['tag_environment_' ~ env_id]
                      | intersect(groups.tags.['tag_clusterid_' ~ cluster_id]
                                  | intersect( groups.tags.['tag_host-type_master'])) }}"
    node_hosts: "{{ groups.tags.['tag_environment_' ~ env_id]
                    | intersect(groups.tags.['tag_clusterid_' ~ cluster_id]
                                | intersect(groups.tags.['tag_host-type_node'])) }}"
  become: no
  tasks:
  - name: wait for ssh
    wait_for: "port=22 host={{ item }}"
    with_items: "{{ env_cluster_hosts }}"

  - name: Add masters to requisite groups
    add_host:
      name: "{{ item }}"
      groups: masters, etcd, nodes, cluster_hosts, OSEv3
      openshift_node_labels:
        region: "{{ hostvars[item].ec2_region }}"
        zone: "{{ hostvars[item].ec2_placement }}"
    with_items: "{{ master_hosts }}"

  - name: Add nodes to requisite groups
    add_host:
      name: "{{ item }}"
      groups: nodes, cluster_hosts, OSEv3
      openshift_node_labels:
        region: "{{ hostvars[item].ec2_region }}"
        zone: "{{ hostvars[item].ec2_placement }}"
    with_items: "{{ node_hosts }}"

