---
ec2_region: us-east-1
ec2_image: ami-7e14f213

identity_providers:
- name: htpasswd_auth
  login: true
  challenge: true
  kind: HTPasswdPasswordIdentityProvider
  filename: /etc/origin/master/htpasswd

os_defaults:
  masters:
    count: "{{ num_masters | default(3) }}"
    instance_type: m4.xlarge
    vol_sizes:
      root: 15
      docker: 25
      etcd: 25
  infra_nodes:
    count: "{{ num_infra_nodes | default(2) }}"
    instance_type: m4.xlarge
    vol_sizes:
      root: 30
      docker: 25
  app_nodes:
    count: "{{ num_app_nodes | default(2) }}"
    instance_type: m4.xlarge
    vol_sizes:
      root: 30
      docker: 25
  hosted:
    vol_sizes:
      registry: 30
      logging: 30
      metrics: 30

provider_defaults:
  ec2:
    tags:
      env: "{{ cluster_id }}"
    groups: ["tag_env_{{ cluster_id }}"]
    master:
      groups:
      - "tag_openshift-master_{{ cluster_id }}"
      - "tag_openshift-node_{{ cluster_id }}"
      - tag_node-region_master
      security_groups:
      - "{{ cluster_id }}-master"
      - "{{ cluster_id }}-node"
      tags:
        openshift-master: "{{ cluster_id }}"
        openshift-node: "{{ cluster_id }}"
        node-region: master
    node:
      groups:
      - "tag_openshift-node_{{ cluster_id }}"
      security_groups:
      - "{{ cluster_id }}-node"
      tags:
        openshift-node: "{{ cluster_id }}"
