---
- name: Create VPC and subnets
  ec2_vpc:
    state: present
    cidr_block: "{{ cidr_block }}"
    resource_tags: { "Name":"{{ vpc_prefix }}" }
    subnets:
      - cidr: "{{ private_sub1 }}"
        az: "{{ lookup('az1', region) }}"
        resource_tags: {"Name": "{{ private_subnet_prefix }}-1" }
      - cidr: "{{ private_sub2 }}"
        az: "{{ lookup('az2', region) }}"
        resource_tags: {"Name": "{{ private_subnet_prefix }}-2" }
      - cidr: "{{ private_sub3 }}"
        resource_tags: {"Name": "{{ private_subnet_prefix }}-3" }
        az: "{{ lookup('az3', region) }}"
      - cidr: "{{ public_sub1 }}"
        resource_tags: { "Name": "{{ public_subnet_prefix }}-1" }
        az: "{{ lookup('az1', region) }}"
      - cidr: "{{ public_sub2 }}"
        resource_tags: { "Name": "{{ public_subnet_prefix }}-2" }
        az: "{{ lookup('az2', region) }}"
      - cidr: "{{ public_sub3 }}"
        resource_tags: { "Name": "{{ public_subnet_prefix }}-3" }
        az: "{{ lookup('az3', region) }}"
    internet_gateway: True
    route_tables:
      - subnets:
          - "{{ public_sub1 }}"
          - "{{ public_sub2 }}"
          - "{{ public_sub3 }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    region: "{{ region }}"
  register: vpc
- name: Tag VPC with name
  ec2_tag:
    resource: "{{vpc.vpc_id}}"
    region: "{{ region }}"
    state: present
    tags:
        Name: "{{ vpc_prefix }}"
- name: Find the first public subnet
  set_fact: private_subnet1="{{item.id}}"
  when: item.resource_tags.Name == "{{ private_subnet_prefix }}-1"
  with_items: vpc.subnets
- name: Find the second public subnet
  set_fact: private_subnet2="{{item.id}}"
  when: item.resource_tags.Name == "{{ private_subnet_prefix }}-2"
  with_items: vpc.subnets
- name: Find the third public subnet
  set_fact: private_subnet3="{{item.id}}"
  when: item.resource_tags.Name == "{{ private_subnet_prefix }}-3"
  with_items: vpc.subnets
- name: Find the third private subnet
  set_fact: public_subnet1="{{item.id}}"
  when: item.resource_tags.Name == "{{ public_subnet_prefix }}-1"
  with_items: vpc.subnets
- name: Find the third private subnet
  set_fact: public_subnet2="{{item.id}}"
  when: item.resource_tags.Name == "{{ public_subnet_prefix }}-2"
  with_items: vpc.subnets
- name: Find the third private subnet
  set_fact: public_subnet3="{{item.id}}"
  when: item.resource_tags.Name == "{{ public_subnet_prefix }}-3"
  with_items: vpc.subnets
- name: Change the fact name
  set_fact: vpc="{{vpc.vpc_id}}"
